name: CI and Super Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Super Linter
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run Super Linter
      - name: Run Super Linter
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true  # Optional: Lint the entire codebase
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  # Optional: Only warnings, no     
