name: notification_unittests

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your dependencies        

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Run your tests
          coverage run -m unittest discover -s tests  # Run tests with coverage
          coverage report  # Display coverage report in the console
          coverage html  # Create an HTML report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/  # Path to the generated HTML coverage report

      - name: Notify on failure
        if: failure()
        run: |
          echo "Tests failed! Please check the logs."
