name: notification_unittests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: Set up environment variables
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: |
          echo "Environment variables set."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/notification/requirements.txt       

      - name: Run unit tests
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: |
          cd backend/notification
          python -m unittest discover -s tests  # Run your tests
          coverage run -m unittest discover -s tests  # Run tests with coverage
          coverage report  # Display coverage report in the console
          coverage html  # Create an HTML report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/  # Path to the generated HTML coverage report
          
      - name: Upload Test Status
        run: echo "status=completed" > test-status.txt
      - name: Upload test status artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-status
          path: test-status.txt

      - name: Notify on failure
        if: failure()
        run: |
          echo "Tests failed! Please check the logs."
