# .github/workflows/notify_on_completion.yml
name: Notify on Completion

on:
  workflow_run:
    workflows: ["CI and Super Linter", "notification_unittests"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Download Linter Status
        uses: actions/download-artifact@v4
        with:
          name: linter-status

      - name: Download Test Status
        uses: actions/download-artifact@v4
        with:
          name: test-status

      - name: Check statuses and Notify Slack
        run: |
          LINTER_STATUS=$(cat linter-status.txt)
          TEST_STATUS=$(cat test-status.txt)

          # Determine overall status
          if [[ "$LINTER_STATUS" == "completed" && "$TEST_STATUS" == "completed" ]]; then
            STATUS="Success"
            COLOR="#36a64f"  # Green
          else
            STATUS="Failure"
            COLOR="#ff0000"  # Red
          fi

          # Send Slack notification
          curl -X POST -H 'Content-type: application/json' --data "{
            \"attachments\": [
              {
                \"fallback\": \"GitHub Action: Notify on Completion result - $STATUS\",
                \"color\": \"$COLOR\",
                \"pretext\": \"GitHub Action: *Notify on Completion*\",
                \"title\": \"Status: $STATUS\",
                \"text\": \"Linter Status: $LINTER_STATUS\nTests Status: $TEST_STATUS\",
                \"footer\": \"GitHub Actions\",
                \"ts\": $(date +%s)
              }
            ]
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
